### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [pixel-alex/DreamDance#4]
A very valuable attempt！
How is the motion transfer in the first result generated?
Which script has been run and the pre-training model can be provided?
We look forward to your reply

**Comment by zcdliuwei** [comment]
And requirement file

**Comment by robo-alex** [comment]
Thanks!
We used [Liquid warping GAN with attention](https://github.com/iPERDance/iPERCore) for motion transfer in pipeline 1. Please run the [scripts](https://github.com/iPERDance/iPERCore/blob/main/docs/scripts_runner.md) to obtain the results. It is required to install the libraries of Stable Diffusion, LDM-LAION, CLIPSeg, and Liquid warping GAN with attention to run the pipeline.

**Comment by zcdliuwei** [comment]
> 

Thank you again for your reply
I'll give it a try

**Comment by zcdliuwei** [comment]
I have another question

Can replace the source image with an animation character, and use driving video to make the animation character move, such as dancing.
Have you tried ?

**Comment by robo-alex** [comment]
It does not perform very well with cartoon characters, since the motion transfer model is trained on a dataset of human motion imitation. That is one of the reasons why we designed 2 pipelines.

**Comment by zcdliuwei** [comment]
> It does not perform very well with cartoon characters, since the motion transfer model is trained on a dataset of human motion imitation. That is one of the reasons why we designed 2 pipelines.

Such is the case
I see these two methods:
https://github.com/snap-research/articulated-animation
https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model
The first one has already been tried and performs well in real human scenes, but performs poorly in animation scenes
The second one hasn't been tried yet, but it feels like it should be the same

But frankly, your second result doesn't seem natural and coherent enough.
Another way is to extract the pose of each frame from the dancing video, then use this pose to control the actions of the animation characters, and then synthesize the results into a video
I don't know if this is feasible

**Comment by robo-alex** [comment]
That is right. It is expected to extract poses/keypoints first if you want very smooth and accurate transfer.

**Comment by zcdliuwei** [comment]
> That is right. It is expected to extract poses/keypoints first if you want very smooth and accurate transfer.

I'll give it a try near future
also if you have any progress, hope to publish it, thanks again !
